<h2> Listas y Tuplas </h2>

**Usa typing en todas las funciones que definas**

In [1]:
from typing import List
from typing import Tuple
from typing import Union


#### 0 - Practica

Desempaquetando (o desestructurando) tuplas

In [2]:
nums = (1, 2)
a, b = nums    # a y b pasan a ser integers, pasan a valer 1 y 2
print('a is', a)
print('b is', b)

a is 1
b is 2


In [5]:
nums = 1, 2
print(type(nums))
numbers = [1, 2]
type(numbers)

<class 'tuple'>


list

In [9]:
fruits = ('peach', 'banana', 'watermelon')
fruit_1, fruit_2, fruit_3 = fruits  # los fruit toman valor de las frutas)
print('fruit 1 is', fruit_1)
print('fruit 2 is', fruit_2)
print('fruit 3 is', fruit_3)

fruit 1 is peach
fruit 2 is banana
fruit 3 is watermelon


In [5]:
min_test_score, max_test_score = 0, 10
print(min_test_score)
print(max_test_score)

0
10


Podemos desestructurar un lista de tuplas a medida que iteramos sobre ella:

In [6]:
people = [('Lada', 23), ('Oshimenu', 31), ('Takeshi', 51)]
for person, age in people:
    print('Name is', person + ',', 'age is', age)

Name is Lada, age is 23
Name is Oshimenu, age is 31
Name is Takeshi, age is 51


Eso lo podemos ver cuando usamos la función `enumerate`, que nos proporciona tuplas con los elementos y los índices del iterable:

In [7]:
for i, fruit in enumerate(fruits):
    print(i, fruit)

0 peach
1 banana
2 watermelon


In [8]:
for i, (person, age) in enumerate(people):
    print(i, person, age)

0 Lada 23
1 Oshimenu 31
2 Takeshi 51


**Nota**: No solo podemos iterar sobre listas, sino sobre cualquier objecto iterable. En Python, los objetos iterables tienen el método todos `__iter__`. De la misma forma, también podemos deconstruir los objetos que tengan este método. Con typing se usa `Iterable` para especificar que un argumento o variable es iterable.

In [9]:
fruits.__iter__

<method-wrapper '__iter__' of tuple object at 0x00000293579EB900>

In [10]:
people.__iter__

<method-wrapper '__iter__' of list object at 0x000002935935C540>

La función `zip` nos proporciona un objeto sobre el cual podemos iterar y acceder a los elementos de dos o más iterables en forma de tupla:

In [11]:
for person, fruit in zip(people, fruits):
    print(person[0], 'loves', fruit)

Lada loves peach
Oshimenu loves banana
Takeshi loves watermelon


In [12]:
for (person, age), fruit in zip(people, fruits):
    print(person, 'loves ' + fruit)

Lada loves peach
Oshimenu loves banana
Takeshi loves watermelon


En el caso de que uno de los iterables sea más corto que los otros, `zip` usará la longitud del iterable más corto:

In [13]:
list_1 = [1,2,3]
list_2 = ['a','b','c','d']
list_3 = [True,True,True,True,False]
for element in zip(list_1, list_2, list_3):
    print(element, '- element is a', element.__class__.__name__)

(1, 'a', True) - element is a tuple
(2, 'b', True) - element is a tuple
(3, 'c', True) - element is a tuple


Normalmente, cuando iteramos sobre una lista de tuplas y hay elementos que no vayamos a utilizar, usamos `_` para representar una variable 'vacía':

In [14]:
names = [name for name, _ in people]
ages = [age for _, age in people]
print(names)
print(ages)

['Lada', 'Oshimenu', 'Takeshi']
[23, 31, 51]


Podemos usar `zip(*iterable)` par desempaquetar listas o iterables con tuplas o otros tipos de iterables dentro en tuplas separadas:

In [15]:
names, ages = zip(*people)
print(names)
print(ages)

('Lada', 'Oshimenu', 'Takeshi')
(23, 31, 51)


**Nota:** no se pueden usar los caracteres `(` o `)` para crear tuplas como lo hacemos con list comprehension ya que eso nos devolveria un generador https://wiki.python.org/moin/Generators.

#### 1 - Tablero de juego

A continuación tienes una lista de tuplas que representan un tablero de un juego imaginario. Cada tupla de la llista tiene dos elementos: el nombre de un jugador y su puntuación. Obten las cantidades siguientes:

- El nombre de la persona con la puntuación más alta
- El nombre de la persona con la puntuación más baja
- La puntuación total
- La puntuación media

Escribe una función para cada caso que reciba como argumento una lista de tuplas. Para el typing,  asume que la puntuación siempre es un `float`.

In [23]:
scoreboard = [('David Heredia', 7.85),
              ('Carlos Pérez', 3.626),
              ('Jinping Xi', 10.603),
              ('Luol Deng', 9.91),
              ('Alkatum Fas', 12.02)]

# escribe tu código aquí
# 1 iteraré sobre scoreboard y si [1] > [max_score] --> sustituyo ambos


max_scorer, max_score = (None, 0)

for name, score in scoreboard:
    print(name)
    print(score)

    if score > max_score:
        max_scorer = name
        max_score = score

print("")
print(f"{max_scorer} ha ganado con {max_score}")

    
   # print(score[1])

David Heredia
7.85
Carlos Pérez
3.626
Jinping Xi
10.603
Luol Deng
9.91
Alkatum Fas
12.02

Alkatum Fas ha ganado con 12.02


In [25]:
scoreboard = [('David Heredia', 7.85),
              ('Carlos Pérez', 3.626),
              ('Jinping Xi', 10.603),
              ('Luol Deng', 9.91),
              ('Alkatum Fas', 12.02)]

# escribe tu código aquí
# 1 iteraré sobre scoreboard y si [1] > [max_score] --> sustituyo ambos


max_scorer = None
max_score = 0

for name, score in scoreboard:

    if score > max_score:
        max_scorer = name
        max_score = score

print("")
print(f"{max_scorer} ha ganado con {max_score}")



Alkatum Fas ha ganado con 12.02


In [ ]:
scoreboard = [('David Heredia', 7.85),
              ('Carlos Pérez', 3.626),
              ('Jinping Xi', 10.603),
              ('Luol Deng', 9.91),
              ('Alkatum Fas', 12.02)]

# escribe tu código aquí
# 1 iteraré sobre scoreboard y si [1] < [min_score] --> sustituyo ambos


for name, score in scoreboard


In [26]:
# puntuación total

total = 0

for name, score in scoreboard:
    total = total + score

print(total)
        


44.009


In [27]:
total = 0

for name, score in scoreboard:
    total = total + score

media = total/len(scoreboard)

print(media)

8.8018


#### 2 - Ordenando el juego

Define una función llamada `sort_scoreboard` que reciba de entrada una lista de tuplas con los nombres de los jugadores y sus puntuaciones y devuelva una copia de la lista ordenada en función de los nombres.

*Pista: crea una función llamada `get_name` con un argumento de entrada que reciba una tupla con el nombre y la puntuación y devuelva solo el nombre*

In [ ]:
# escribe tu código aquí

#### 3 - Buenos jugadores

Define una función llamada `good_players` que reciba dos argumentos:

- El tablero con las puntuaciones
- Una puntuación a determinar por el usuario

`good_players` tiene que devolver una lista con los nombres de todos los jugadores con una puntuación más alta o igual que la escogida por el usuario.

In [ ]:
# escribe tu código aquí

#### 4 - Separando tuplas

Define una función llamada `split_scoreboard` que reciba de argumento la lista con los nombres y las puntuaciones del ejercicio 1 y la separe en dos listas usando `zip`. La primera lista tiene que tener el nombre de todos los jugadores y la segunda sus puntuaciones. Usa desempaquetamiento de tuplas y guarda las listas en dos variables llamadas `players` y `scores` fuera de la función. Qué tipo de dato devuelve la función `split_scoreboard`?

In [ ]:
# escribe tu código aquí

#### 5 - Nombres y apellidos

Define una función que separe los nombres de los jugadores en dos listas: una con los nombres y otra con los apellidos.

*Pista: usa el método `.split()` de las strings*

In [ ]:
# escribe tu código aquí

#### 6 - Apellido más largo

Define una función llamada `longest_string` con 2 parámetros de entrada: una lista de strings `list_of_strings` y un booleano `return_length`. El segundo parámetro tiene que ser `False` por defecto. La función `longest_string` tiene que devolver la string más larga de la lista. En el caso que `return_length` sea `True`, `longest_string` tiene que devolver también la longitud de la string más larga, es decir una tupla con la string y su longitud. Comprueba qué devuelve `longest_string` en los dos casos cuando `return_length = False` y `return_length = True` con la lista de apellidos del ejercicio anterior.

In [ ]:
# escribe tu código aquí

#### 7 - Añadir el índice

Ordena el tablero con las puntuaciones del ejercicio 1 de puntuación más baja a más alta. Después, crea un tablero de juego nuevo donde cada tupla tenga tres valores:

- La posición en el ránquing del jugador de acuerdo con su puntuación
- El nombre completo del jugador
- La puntuación del jugador

El tablero final tiene que ser el siguiente:

```python
scoreboard_ranked = [(1, 'Alkatum Fas', 12.02), (2, 'Jinping Xi', 10.603), (3, 'Luol Deng', 9.91), (4, 'David Heredia', 7.85) (5, 'Carlos Pérez', 3.626)]
```

In [ ]:
# escribe tu código aquí

#### 8 - Intercalando tuplas

A continuación tienes las letras del abecedario separadas en dos tuplas de manera intercalada:

- a, c, e, g, i, k, m, o, q, s, u, w, y
- b, d, f, h, j, l, n, p, r, t, v, x, z

Define una tupla nueva llamada `abecedario` con el abecedario ordenado juntando las dos tuplas anteriores.

In [ ]:
ace = ('a', 'c', 'e', 'g', 'i', 'k', 'm', 'o', 'q', 's', 'u', 'w', 'y')
bdf = ('b', 'd', 'f', 'h', 'j', 'l', 'n', 'p', 'r', 't', 'v', 'x', 'z')

# escribe tu código aquí

#### 9 - Inputs de una función

Define una función lamada `loves_chocolate` que reciba tres parámetros de entrada: Un nombre (`str`), una edad (`int`) y si le gusta o no el chocolate (`bool`). La función no tiene que devolver nada, simplemente imprimir el siguiente mensaje:

- En caso que no le guste el chocolate 

```python
nombre + ' is ' + str(edad) +  ' years old and somehow does not like chocolate'
```

- En caso que le guste el chocolate

```python
nombre + ' is ' + str(edad) +  ' years old and loves chocolate'
```

Crea una tupla con los inputs de la función y llama la función `loves_chocolate` deconstruyendo la tupla usando el operador `*`.

In [ ]:
# escribe tu código aquí